CREATE TABLE BL_3NF.CE_EMPLOYEES (
    EMPLOYEE_ID            NUMBER(38) NOT NULL,
    EMPLOYEE_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    EMPLOYEE_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    EMPLOYEE_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    FIRST_NAME             VARCHAR2(50 CHAR) NOT NULL,
    LAST_NAME              VARCHAR2(50 CHAR) NOT NULL,
    DAY_OF_BIRTHDAY        DATE NOT NULL,
    POSITION_ID            NUMBER(38) NOT NULL,
    PHONE                  VARCHAR2(50 CHAR) NOT NULL,
    EMAIL                  VARCHAR2(50 CHAR) NOT NULL,
    ADDRESS                VARCHAR2(50 CHAR) NOT NULL,
    COUNTRY_ID             NUMBER(38) NOT NULL,
    TA_UPDATE_DT           DATE NOT NULL,
    TA_INSERT_DT           DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_EMPLOYEES ADD CONSTRAINT CE_EMPLOYEE_PK PRIMARY KEY ( EMPLOYEE_ID );

ALTER TABLE BL_3NF.CE_EMPLOYEES
    ADD CONSTRAINT CE_EMPLOYEE_CE_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES BL_3NF.CE_COUNTRIES ( COUNTRY_ID );

ALTER TABLE BL_3NF.CE_EMPLOYEES
    ADD CONSTRAINT CE_EMPLOYEE_CE_POSITION_FK FOREIGN KEY ( POSITION_ID )
        REFERENCES BL_3NF.CE_POSITIONS ( POSITION_ID );