CREATE TABLE BL_3NF.CE_CUSTOMERS (
    CUSTOMER_ID            NUMBER(38) NOT NULL,
    CUSTOMER_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    CUSTOMER_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    CUSTOMER_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    FIRST_NAME             VARCHAR2(50 CHAR) NOT NULL,
    LAST_NAME              VARCHAR2(50 CHAR) NOT NULL,
    COMPANY_NAME           VARCHAR2(50 CHAR) NOT NULL,
    COMPANY_NUMBER         VARCHAR2(50 CHAR) NOT NULL,
    PHONE                  VARCHAR2(50 CHAR) NOT NULL,
    GENDER                 VARCHAR2(50 CHAR) NOT NULL,
    YEAR_OF_BIRTHDAY       NUMBER(38) NOT NULL,
    EMAIL                  VARCHAR2(50 CHAR) NOT NULL,
    ADDRESS                VARCHAR2(1000 CHAR) NOT NULL,
    COUNTRY_ID             NUMBER(38) NOT NULL,
    TA_UPDATE_DT           DATE NOT NULL,
    TA_INSERT_DT           DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_CUSTOMERS ADD CONSTRAINT CE_CUSTOMER_PK PRIMARY KEY ( CUSTOMER_ID );

ALTER TABLE BL_3NF.CE_CUSTOMERS
    ADD CONSTRAINT CE_CUSTOMER_CE_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES BL_3NF.CE_COUNTRIES ( COUNTRY_ID );