CREATE TABLE BL_DM.DIM_CHANNELS (
    CHANNEL_SURR_ID     NUMBER(38) NOT NULL,
    CHANNEL_SRCID       VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM       VARCHAR2(50) NOT NULL,
    SOURCE_ENTITY       VARCHAR2(50) NOT NULL,
    CHANNEL_DESCRIPTION VARCHAR2(50) NOT NULL,
    CHANNEL_CLASS_ID    NUMBER(38) NOT NULL,
    CHANNEL_CLASS       VARCHAR2(50) NOT NULL,
    TA_UPDATE_DT        DATE NOT NULL,
    TA_INSERT_DT        DATE NOT NULL
);

ALTER TABLE BL_DM.DIM_CHANNELS ADD CONSTRAINT DIM_CHANNELS_PK PRIMARY KEY ( CHANNEL_SURR_ID );