--Create test table---
CREATE TABLE BL_CL.TEMP_PRODUCTS (
    PRODUCT_SURR_ID  NUMBER(38) NOT NULL,
    PRODUCT_SRCID    VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM    VARCHAR2(50) NOT NULL,
    SOURCE_ENTITY    VARCHAR2(50) NOT NULL,
    PRODUCT_NAME     VARCHAR2(2000) NOT NULL,
    PRODUCT_BRAND_ID NUMBER(38) NOT NULL,
    PRODUCT_BRAND    VARCHAR2(50) NOT NULL,
    PRODUCT_TYPE_ID  NUMBER(38) NOT NULL,
    PRODUCT_TYPE     VARCHAR2(50) NOT NULL,
    TA_UPDATE_DT     DATE NOT NULL,
    TA_INSERT_DT     DATE NOT NULL
);
     DELETE FROM BL_CL.TEMP_PRODUCTS

--Create test procedure for using  cursor FOR loop---
CREATE OR REPLACE PROCEDURE INSERTMDCGENERAL AS
BEGIN
    FOR R_PRODUCT IN (
        SELECT
            *
        FROM
            DIM_PRODUCTS
        WHERE
            PRODUCT_TYPE_ID = 3
    ) LOOP
        INSERT INTO BL_CL.TEMP_PRODUCTS (
            PRODUCT_SURR_ID,
            PRODUCT_SRCID,
            SOURCE_SYSTEM,
            SOURCE_ENTITY,
            PRODUCT_NAME,
            PRODUCT_BRAND_ID,
            PRODUCT_BRAND,
            PRODUCT_TYPE_ID,
            PRODUCT_TYPE,
            TA_UPDATE_DT,
            TA_INSERT_DT
        ) VALUES (
            R_PRODUCT.PRODUCT_SURR_ID,
            R_PRODUCT.PRODUCT_SRCID,
            R_PRODUCT.SOURCE_SYSTEM,
            R_PRODUCT.SOURCE_ENTITY,
            R_PRODUCT.PRODUCT_NAME,
            R_PRODUCT.PRODUCT_BRAND_ID,
            R_PRODUCT.PRODUCT_BRAND,
            R_PRODUCT.PRODUCT_TYPE_ID,
            R_PRODUCT.PRODUCT_TYPE,
            R_PRODUCT.TA_UPDATE_DT,
            R_PRODUCT.TA_INSERT_DT
        );

    END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END INSERTMDCGENERAL;

EXEC INSERTMDCGENERAL;