CREATE TABLE BL_3NF.CE_COUNTRIES (
    COUNTRY_ID            NUMBER(38) NOT NULL,
    COUNTRY_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    COUNTRY_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    COUNTRY_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    COUNTRY               VARCHAR2(50 CHAR) NOT NULL,
    TA_UPDATE_DT          DATE NOT NULL,
    TA_INSERT_DT          DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_COUNTRIES ADD CONSTRAINT CE_COUNTRIES_PK PRIMARY KEY ( COUNTRY_ID );