CREATE TABLE BL_3NF.CE_BRANDS (
    PRODUCT_BRAND_ID            NUMBER(38) NOT NULL,
    PRODUCT_BRAND_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_BRAND_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_BRAND_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_BRAND               VARCHAR2(50 CHAR) NOT NULL,
    TA_UPDATE_DT                DATE NOT NULL,
    TA_INSERT_DT                DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_BRANDS ADD CONSTRAINT CE_PRODUCT_BRAND_PK PRIMARY KEY ( PRODUCT_BRAND_ID );
