CREATE TABLE BL_3NF.CE_STORES (
    STORE_ID            NUMBER(38) NOT NULL,
    STORE_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    STORE_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    STORE_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PHONE               VARCHAR2(50 CHAR) NOT NULL,
    ADDRESS_ID          NUMBER(38) NOT NULL,
    TA_UPDATE_DT        DATE NOT NULL,
    TA_INSERT_DT        DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_STORES ADD CONSTRAINT CE_STORE_PK PRIMARY KEY ( STORE_ID );

ALTER TABLE BL_3NF.CE_STORES
    ADD CONSTRAINT CE_STORE_CE_ADDRESS_FK FOREIGN KEY ( ADDRESS_ID )
        REFERENCES BL_3NF.CE_ADDRESSES ( ADDRESS_ID );