ALTER SESSION SET NLS_DATE_FORMAT='yyyy-mm-dd hh24:mi:ss';

CREATE TABLE BL_CL.PRM_MTA_INCREMENTAL_LOAD (
    SA_TABLE_NAME           VARCHAR2(100) NOT NULL,
    TARGET_TABLE_NAME       VARCHAR2(100) NOT NULL,
    PACKAGE                 VARCHAR2(100) NOT NULL,
    PROCEDURE               VARCHAR2(100) NOT NULL,
    PREVIOUS_LOADED_DATE    DATE NOT NULL
);