CREATE TABLE BL_3NF.CE_PROMOTIONS_SCD (
    PROMOTION_ID            NUMBER(38) NOT NULL,
    PROMOTION_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_NAME          VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_CATEGORY_ID   NUMBER(38) NOT NULL,
    START_DT                DATE NOT NULL,
    END_DT                  DATE NOT NULL,
    IS_ACTIVE               VARCHAR2(50 CHAR) NOT NULL,
    COST                    NUMBER(15, 2) NOT NULL,
    TA_UPDATE_DT            DATE NOT NULL,
    TA_INSERT_DT            DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_PROMOTIONS_SCD ADD CONSTRAINT CE_PROMOTIONS_SCD_PK PRIMARY KEY ( PROMOTION_ID,
                                                                                       START_DT );

ALTER TABLE BL_3NF.CE_PROMOTIONS_SCD
    ADD CONSTRAINT CE_PROMOTIONS_SCD_CE_PROMOTION_CLASS_FK FOREIGN KEY ( PROMOTION_CATEGORY_ID )
        REFERENCES BL_3NF.CE_PROMOTION_CATEGORIES ( PROMOTION_CATEGORY_ID );
