CREATE TABLE BL_DM.DIM_STORES (
    STORE_SURR_ID  NUMBER(38)   NOT NULL,
    STORE_SRCID    VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM  VARCHAR2(50) NOT NULL,
    SOURCE_ENTITY  VARCHAR2(50) NOT NULL,
    PHONE          VARCHAR2(50) NOT NULL,
    STREET_ADDRESS VARCHAR2(2000) NOT NULL,
    POSTAL_CODE    VARCHAR2(50) NOT NULL,
    CITY_ID        NUMBER(38)   NOT NULL,
    CITY           VARCHAR2(50) NOT NULL,
    STATE_ID       NUMBER(38)   NOT NULL,
    STATE          VARCHAR2(50) NOT NULL,
    COUNTRY_ID     NUMBER(38)   NOT NULL,
    COUNTRY        VARCHAR2(50) NOT NULL,
    TA_UPDATE_DT   DATE         NOT NULL,
    TA_INSERT_DT   DATE         NOT NULL
);

ALTER TABLE BL_DM.DIM_STORES ADD CONSTRAINT DIM_STORES_PK PRIMARY KEY ( STORE_SURR_ID );
