SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_CHANNELS;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_COUNTRIES;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_CUSTOMERS;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_EMPLOYEES;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_PRODUCTS;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_PROMOTIONS;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_STORES;
SELECT * FROM SA_SOURCE_SYSTEM_1.SRC_SALES;



SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_CHANNELS;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_COUNTRIES;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_CUSTOMERS;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_EMPLOYEES;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_PRODUCTS;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_PROMOTIONS;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_STORES;
SELECT * FROM SA_SOURCE_SYSTEM_2.SRC_SALES;





DELETE FROM CE_SALES WHERE S
DELETE FROM CE_CHANNELS WHERE CHANNEL_ID!=-1;
DELETE FROM CE_CHANNEL_CLASSES WHERE CHANNEL_CLASS_ID!=-1;
DELETE FROM CE_PROMOTIONS_SCD WHERE PROMOTION_ID!=-1; 
DELETE FROM CE_PROMOTION_CATEGORIES WHERE PROMOTION_CATEGORY_ID!=-1;
DELETE FROM CE_PRODUCTS WHERE PRODUCT_ID!=-1;
DELETE FROM CE_BRANDS WHERE BRAND_ID !=-1;
DELETE FROM CE_PRODUCT_TYPES WHERE PRODUCT_TYPE_ID!=-1;

DELETE FROM CE_CUSTOMERS WHERE CUSTOMER_ID!=-1;
DELETE FROM CE_EMPLOYEES WHERE EMPLOYEE_ID!=-1;
DELETE FROM CE_POSITIONS WHERE POSITION_ID!=-1;
DELETE FROM CE_STORES WHERE STORE_ID!=-1;
DELETE FROM CE_ADDRESSES WHERE ADDRESS_ID!=-1;
DELETE FROM CE_CITIES WHERE CITY_ID!=-1;
DELETE FROM CE_STATES WHERE STATE_ID!=-1;
DELETE FROM CE_COUNTRIES WHERE COUNTRY_ID!=-1;




SELECT * FROM CE_CHANNEL_CLASSES;
SELECT * FROM CE_CHANNELS; 
SELECT * FROM CE_PROMOTION_CATEGORIES;
--select * from CE_PROMOTIONS_SCD;
SELECT * FROM CE_BRANDS;
SELECT * FROM CE_PRODUCT_TYPES;
SELECT * FROM CE_PRODUCTS;
SELECT * FROM CE_COUNTRIES;
SELECT * FROM CE_STATES;
SELECT * FROM CE_CITIES;
SELECT * FROM CE_ADDRESSES;
SELECT * FROM CE_STORES;
SELECT * FROM CE_CUSTOMERS;
SELECT * FROM CE_POSITIONS;
SELECT * FROM CE_EMPLOYEES

SELECT * FROM BL_CL.LOG_TABLE;

TRUNCATE TABLE BL_CL.LOG_TABLE;
COMMIT