-----------------LOAD SRC FROM 1 SOURCE-----------------------------------------
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_CHANNELS;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_COUNTRIES;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_CUSTOMERS;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_EMPLOYEES;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_PRODUCTS;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_PROMOTIONS;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_STORES;
EXEC PKG_LOAD_SRC_1_TABLES.PRC_LOAD_SRC_1_SALES;
--------------------------------------------------------------------------------

-----------------LOAD SRC FROM 2 SOURCE-----------------------------------------
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_CHANNELS;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_COUNTRIES;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_CUSTOMERS;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_EMPLOYEES;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_PRODUCTS;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_PROMOTIONS;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_STORES;
EXEC PKG_LOAD_SRC_2_TABLES.PRC_LOAD_SRC_2_SALES;
--------------------------------------------------------------------------------
--------------LOAD 3NF LAYER----------------------------------------------------   
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_CHANNEL_CLASSES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_CHANNELS; 
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_PROMOTION_CATEGORIES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_PROMOTIONS_SCD;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_BRANDS;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_PRODUCT_TYPES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_PRODUCTS;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_COUNTRIES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_STATES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_CITIES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_ADDRESSES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_STORES;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_CUSTOMERS;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_POSITIONS;
EXEC PKG_LOAD_3NF_TABLES.PRC_LOAD_CE_EMPLOYEES;
    
--------------------------------------------------------------------------------
--------------LOAD BL_DM LAYER--------------------------------------------------
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_CHANNELS;
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_PROMOTIONS_SCD;
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_PRODUCTS;
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_STORES;
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_CUSTOMERS;
EXEC PKG_LOAD_BL_DM_TABLES.PRC_LOAD_DIM_EMPLOYEES;

--------------------------------------------------------------------------------


EXEC PKG_LOAD_FCT_SALES_INIT.PRC_LOAD_CE_SALES_INIT(TO_DATE('2020-01-01', 'yyyy-mm-dd'),TO_DATE('2021-10-01', 'yyyy-mm-dd'));
EXEC PKG_LOAD_FCT_SALES_INIT.PRC_LOAD_FCT_SALES_INIT(TO_DATE('2020-01-01', 'yyyy-mm-dd'),TO_DATE('2021-10-01', 'yyyy-mm-dd'));








EXEC PKG_LOAD_FCT_SALES.PRC_LOAD_CE_SALES(TO_DATE('2021-10-01', 'yyyy-mm-dd'),TO_DATE('2022-01-01', 'yyyy-mm-dd'));
EXEC PKG_LOAD_FCT_SALES.PRC_LOAD_FCT_SALES(TO_DATE('2021-10-01', 'yyyy-mm-dd'),TO_DATE('2022-01-01', 'yyyy-mm-dd'));


-------------------------------TESTS--------------------------------------------
EXEC TEST_DUBLES; 

SELECT * FROM BL_CL.TEST_RESULTS_DUBLES;

