CREATE TABLE BL_3NF.CE_STATES (
    STATE_ID            NUMBER(38) NOT NULL,
    STATE_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    STATE_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    STATE_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    STATE_NAME          VARCHAR2(50 CHAR) NOT NULL,
    COUNTRY_ID          NUMBER(38) NOT NULL,
    TA_UPDATE_DT        DATE NOT NULL,
    TA_INSERT_DT        DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_STATES ADD CONSTRAINT CE_STATE_PK PRIMARY KEY ( STATE_ID );

ALTER TABLE BL_3NF.CE_STATES
    ADD CONSTRAINT CE_STATE_CE_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES BL_3NF.CE_COUNTRIES ( COUNTRY_ID );