CREATE OR REPLACE PACKAGE PKG_LOAD_BL_DM_TABLES IS
    L_PACKAGE_NAME CONSTANT VARCHAR2(100) := 'pkg_load_bl_dm_tables';
    PROCEDURE PRC_LOAD_DIM_CHANNELS;
    PROCEDURE PRC_LOAD_DIM_PROMOTIONS_SCD;
    PROCEDURE PRC_LOAD_DIM_PRODUCTS;
    PROCEDURE PRC_LOAD_DIM_STORES;
    PROCEDURE PRC_LOAD_DIM_CUSTOMERS;
    PROCEDURE PRC_LOAD_DIM_EMPLOYEES;

END;