CREATE TABLE BL_3NF.CE_ADDRESSES (
    ADDRESS_ID            NUMBER(38) NOT NULL,
    ADDRESS_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    ADDRESS_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    ADDRESS_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    STREET_ADDRESS        VARCHAR2(1000 CHAR) NOT NULL,
    POSTAL_CODE           VARCHAR2(50 CHAR) NOT NULL,
    CITY_ID               NUMBER(38) NOT NULL,
    TA_UPDATE_DT          DATE NOT NULL,
    TA_INSERT_DT          DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_ADDRESSES ADD CONSTRAINT CE_ADDRESS_PK PRIMARY KEY ( ADDRESS_ID );

ALTER TABLE BL_3NF.CE_ADDRESSES
    ADD CONSTRAINT CE_ADDRESSES_CE_CITY_FK FOREIGN KEY ( CITY_ID )
        REFERENCES BL_3NF.CE_CITIES ( CITY_ID );