CREATE TABLE BL_3NF.CE_PRODUCTS (
    PRODUCT_ID            NUMBER(38) NOT NULL,
    PRODUCT_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT               VARCHAR2(1000 CHAR) NOT NULL,
    UNIT_PRICE            NUMBER(15, 2) NOT NULL,
    UNIT_COST             NUMBER(15, 2) NOT NULL,
    PRODUCT_BRAND_ID      NUMBER(38) NOT NULL,
    PRODUCT_TYPE_ID       NUMBER(38) NOT NULL,
    TA_UPDATE_DT          DATE NOT NULL,
    TA_INSERT_DT          DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_PRODUCTS ADD CONSTRAINT CE_PRODUCT_PK PRIMARY KEY ( PRODUCT_ID );

ALTER TABLE BL_3NF.CE_PRODUCTS
    ADD CONSTRAINT CE_PRODUCTS_CE_BRAND_FK FOREIGN KEY ( PRODUCT_BRAND_ID )
        REFERENCES BL_3NF.CE_BRANDS ( PRODUCT_BRAND_ID );

ALTER TABLE BL_3NF.CE_PRODUCTS
    ADD CONSTRAINT CE_PRODUCTS_CE_PRODUCT_TYPE_FK FOREIGN KEY ( PRODUCT_TYPE_ID )
        REFERENCES BL_3NF.CE_PRODUCT_TYPES ( PRODUCT_TYPE_ID );