DROP TABLE SA_SOURCE_SYSTEM_1.SRC_SALES ;
CREATE TABLE SA_SOURCE_SYSTEM_1.SRC_SALES(
 product_id VARCHAR2(100),
 customer_id VARCHAR2(100),
 channel_id VARCHAR2(100),
 promo_id VARCHAR2(100),
 employee_id VARCHAR2(100),
 store_id VARCHAR2(100),
 quantity_sold VARCHAR2(100),
 time_id VARCHAR2(100),
 TA_UPDATE_DT DATE NOT NULL,
 TA_INSERT_DT DATE NOT NULL
);
