CREATE TABLE BL_3NF.CE_SALES (
    SALE_ID            NUMBER(38) NOT NULL,
    SALE_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    SALE_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PRODUCT_ID         NUMBER(38) NOT NULL,
    DATE_ID            DATE NOT NULL,
    PROMOTION_ID       NUMBER(38) NOT NULL,
    CHANNEL_ID         NUMBER(38) NOT NULL,
    STORE_ID           NUMBER(38) NOT NULL,
    EMPLOYEE_ID        NUMBER(38) NOT NULL,
    CUSTOMER_ID        NUMBER(38) NOT NULL,
    SALE_COST          NUMBER(15, 3),
    SALE_PRICE         NUMBER(15, 3),
    SALE_QUANTITY      NUMBER(38),
    TA_UPDATE_DT       DATE NOT NULL,
    TA_INSERT_DT       DATE NOT NULL
)
PARTITION BY RANGE (DATE_ID)
(
    PARTITION sales_before_2000 VALUES LESS THAN (to_date('2000-01-01','yyyy-mm-dd'))
);



ALTER TABLE BL_3NF.CE_SALES
    ADD CONSTRAINT CE_SALES_CE_PRODUCT_FK FOREIGN KEY ( PRODUCT_ID )
        REFERENCES BL_3NF.CE_PRODUCTS ( PRODUCT_ID );

ALTER TABLE BL_3NF.CE_SALES
    ADD CONSTRAINT CE_SALES_CE_CHANNEL_FK FOREIGN KEY ( CHANNEL_ID )
        REFERENCES BL_3NF.CE_CHANNELS ( CHANNEL_ID );

ALTER TABLE BL_3NF.CE_SALES
    ADD CONSTRAINT CE_SALES_CE_STORE_FK FOREIGN KEY ( STORE_ID )
        REFERENCES BL_3NF.CE_STORES ( STORE_ID );

ALTER TABLE BL_3NF.CE_SALES
    ADD CONSTRAINT CE_SALES_CE_EMPLOYEE_FK FOREIGN KEY ( EMPLOYEE_ID )
        REFERENCES BL_3NF.CE_EMPLOYEES ( EMPLOYEE_ID );

ALTER TABLE BL_3NF.CE_SALES
    ADD CONSTRAINT CE_SALES_CE_CUSTOMER_FK FOREIGN KEY ( CUSTOMER_ID )
        REFERENCES BL_3NF.CE_CUSTOMERS ( CUSTOMER_ID );