CREATE OR REPLACE PACKAGE PKG_LOAD_SRC_1_TABLES IS
    L_PACKAGE_NAME CONSTANT VARCHAR2(100) := 'pkg_load_src_1_tables';
    PROCEDURE PRC_LOAD_SRC_1_CHANNELS; 
    PROCEDURE PRC_LOAD_SRC_1_Countries; 
    PROCEDURE PRC_LOAD_SRC_1_CUSTOMERS;
    PROCEDURE PRC_LOAD_SRC_1_EMPLOYEES;
    PROCEDURE PRC_LOAD_SRC_1_PRODUCTS;
    PROCEDURE PRC_LOAD_SRC_1_PROMOTIONS;
    PROCEDURE PRC_LOAD_SRC_1_STORES;
    PROCEDURE PRC_LOAD_SRC_1_SALES;



END;