alter session set "_ORACLE_SCRIPT"=true; 
--CREATE USERS FOR HOMEWORKS AND FOR 2 SOURCES
CREATE USER SOURCE_ABSTRACTION
IDENTIFIED BY test;

CREATE USER SA_SOURCE_SYSTEM_1
IDENTIFIED BY SA_SOURCE_SYSTEM_1;

CREATE USER SA_SOURCE_SYSTEM_2
IDENTIFIED BY SA_SOURCE_SYSTEM_2;

--GRANT PRIVILEGES TO USERS
GRANT CONNECT, RESOURCE TO SOURCE_ABSTRACTION;
GRANT CONNECT, RESOURCE TO SA_SOURCE_SYSTEM_1;
GRANT CONNECT, RESOURCE TO SA_SOURCE_SYSTEM_2;

--CHECK USERS EXISTS
SELECT * FROM ALL_USERS WHERE (USERNAME LIKE 'SOURCE_%' OR  USERNAME LIKE 'SA_SOURCE_%');


--create directories and grant privileges to users
CREATE DIRECTORY SOURCE_GEO
    AS '/opt/oracle/oradata/Geo_data';
GRANT READ, WRITE ON DIRECTORY SOURCE_GEO TO SOURCE_ABSTRACTION;

CREATE DIRECTORY SOURCE_1
    AS '/opt/oracle/oradata/Sourse_1_data';
GRANT READ, WRITE ON DIRECTORY SOURCE_1 TO SA_SOURCE_SYSTEM_1;

CREATE DIRECTORY SOURCE_2
    AS '/opt/oracle/oradata/Sourse_2_data';
GRANT READ, WRITE ON DIRECTORY SOURCE_2 TO SA_SOURCE_SYSTEM_2;

-- check directories
SELECT * FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME LIKE 'SOURCE_%';

-- check privileges for directories
SELECT GRANTEE,TABLE_NAME, PRIVILEGE  FROM USER_TAB_PRIVS WHERE TABLE_NAME LIKE 'SOURCE_%' ;