CREATE TABLE BL_CL.MAP_CHANNELS (
    CHANNEL_ID            NUMBER(38) NOT NULL,
    CHANNEL_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_DESCRIPTION   VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_CLASS_ID      NUMBER(38) NOT NULL,
    TA_UPDATE_DT          DATE NOT NULL,
    TA_INSERT_DT          DATE NOT NULL
);