CREATE OR REPLACE PACKAGE PKG_LOAD_SRC_2_TABLES IS
    L_PACKAGE_NAME CONSTANT VARCHAR2(100) := 'pkg_load_src_2_tables';
    PROCEDURE PRC_LOAD_SRC_2_CHANNELS; 
    PROCEDURE PRC_LOAD_SRC_2_Countries; 
    PROCEDURE PRC_LOAD_SRC_2_CUSTOMERS;
    PROCEDURE PRC_LOAD_SRC_2_EMPLOYEES;
    PROCEDURE PRC_LOAD_SRC_2_PRODUCTS;
    PROCEDURE PRC_LOAD_SRC_2_PROMOTIONS;
    PROCEDURE PRC_LOAD_SRC_2_STORES;
    PROCEDURE PRC_LOAD_SRC_2_SALES;



END;