CREATE TABLE BL_3NF.CE_POSITIONS (
    POSITION_ID            NUMBER(38) NOT NULL,
    POSITION_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    POSITION_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    POSITION_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    POSITION               VARCHAR2(50 CHAR) NOT NULL,
    TA_UPDATE_DT           DATE NOT NULL,
    TA_INSERT_DT           DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_POSITIONS ADD CONSTRAINT CE_POSITIONS_PK PRIMARY KEY ( POSITION_ID );
