CREATE TABLE BL_3NF.CE_PROMOTION_CATEGORIES (
    PROMOTION_CATEGORY_ID            NUMBER(38) NOT NULL,
    PROMOTION_CATEGORY_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_CATEGORY_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_CATEGORY_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    PROMOTION_CATEGORY               VARCHAR2(50 CHAR) NOT NULL,
    TA_UPDATE_DT                     DATE NOT NULL,
    TA_INSERT_DT                     DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_PROMOTION_CATEGORIES ADD CONSTRAINT CE_PROMOTION_CATEGORY_PK PRIMARY KEY ( PROMOTION_CATEGORY_ID );
