alter session set "_oracle_script"=true;

CREATE USER BL_3NF IDENTIFIED BY BL_3NF;
CREATE USER BL_DM IDENTIFIED BY BL_DM;

CREATE USER BL_CL IDENTIFIED BY BL_CL;

-- Grant priveleges
GRANT connect TO BL_CL;
GRANT connect TO BL_3NF;
GRANT connect TO BL_DM;

-- Check if users were created
SELECT * FROM all_users WHERE USERNAME LIKE 'BL_%';

-- Grant tablespace quota to the user
ALTER user BL_CL quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO BL_CL;
ALTER user SA_SOURCE_SYSTEM_1 quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO SA_SOURCE_SYSTEM_1;
ALTER user SA_SOURCE_SYSTEM_2 quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO SA_SOURCE_SYSTEM_2;

ALTER user BL_3NF quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO BL_3NF;
ALTER user BL_DM quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO BL_DM;

-- Grant read, write to BL_CL on source directories
GRANT READ, WRITE ON DIRECTORY SOURCE_1 TO BL_CL;
GRANT READ, WRITE ON DIRECTORY SOURCE_2 TO BL_CL;


-- Grant select, insert, delete, update to BL_CL
GRANT SELECT ANY TABLE TO BL_CL;
GRANT INSERT ANY TABLE TO BL_CL;
GRANT DELETE ANY TABLE TO BL_CL;
GRANT DROP ANY TABLE TO BL_CL;
GRANT UPDATE ANY TABLE TO BL_CL;
GRANT CREATE ANY TABLE TO BL_CL;
GRANT alter ANY TABLE TO BL_CL;
GRANT CREATE ANY SYNONYM to BL_CL;
GRANT CREATE PUBLIC SYNONYM to BL_CL;
-- Grant select any sequence
GRANT ALTER ANY SEQUENCE, SELECT ANY SEQUENCE TO BL_CL;

GRANT SELECT ANY TABLE TO BL_3NF;
GRANT INSERT ANY TABLE TO BL_3NF;
GRANT DELETE ANY TABLE TO BL_3NF;
GRANT UPDATE ANY TABLE TO BL_3NF;
GRANT CREATE ANY TABLE TO BL_3NF;
GRANT alter ANY TABLE TO BL_3NF;
GRANT CREATE ANY SYNONYM to BL_3NF;
GRANT CREATE PUBLIC SYNONYM to BL_3NF;
-- Grant select any sequence
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, SELECT ANY SEQUENCE TO BL_3NF;


GRANT SELECT ANY TABLE TO BL_DM;
GRANT INSERT ANY TABLE TO BL_DM;
GRANT DELETE ANY TABLE TO BL_DM;
GRANT UPDATE ANY TABLE TO BL_DM;
GRANT CREATE ANY TABLE TO BL_DM;
GRANT alter ANY TABLE TO BL_DM;
-- Grant select any sequence
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, SELECT ANY SEQUENCE TO BL_DM;

