SELECT PRODUCT_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT PRODUCT_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(PRODUCT_SRCID) AS PR FROM CE_PRODUCTS;

SELECT CHANNEL_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT CHANNEL_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(M.CHANNEL_SRCID) AS PR FROM CE_CHANNELS C
INNER JOIN bl_cl.MAP_CHANNELS M
ON m.channel_id=c.channel_srcid;

SELECT CUSTOMER_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT CUSTOMER_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(CUSTOMER_SRCID) AS PR FROM CE_CUSTOMERS;

SELECT EMPLOYEE_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT EMPLOYEE_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(EMPLOYEE_SRCID) AS PR FROM CE_EMPLOYEES;

SELECT PROMO_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT PROMO_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(PROMOTION_SRCID) AS PR FROM BL_3NF.ce_promotions_scd;

SELECT STORE_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
UNION
SELECT STORE_ID AS PR FROM SA_SOURCE_SYSTEM_1.SRC_SALES 
MINUS
SELECT TO_CHAR(STORE_SRCID) AS PR FROM CE_STORES;


