CREATE TABLE BL_DM.DIM_CUSTOMERS (
    CUSTOMER_SURR_ID NUMBER(38)     NOT NULL,
    CUSTOMER_SRCID   VARCHAR2(50)   NOT NULL,
    SOURCE_SYSTEM    VARCHAR2(50)   NOT NULL,
    SOURCE_ENTITY    VARCHAR2(50)   NOT NULL,
    FIRST_NAME       VARCHAR2(50)   NOT NULL,
    LAST_NAME        VARCHAR2(50)   NOT NULL,
    COMPANY_NAME     VARCHAR2(50)   NOT NULL,
    PHONE            VARCHAR2(50)   NOT NULL,
    COMPANY_NUMBER   VARCHAR2(50)   NOT NULL,
    GENDER           VARCHAR2(50)   NOT NULL,
    YEAR_OF_BIRTH   NUMBER(38)     NOT NULL,
    EMAIL            VARCHAR2(50)   NOT NULL,
    COUNTRY          VARCHAR2(50)   NOT NULL,
    COUNTRY_ID       NUMBER(38)     NOT NULL,
    ADDRESS          VARCHAR2(2000)   NOT NULL,
    TA_UPDATE_DT     DATE           NOT NULL,
    TA_INSERT_DT     DATE           NOT NULL
);

ALTER TABLE BL_DM.DIM_CUSTOMERS ADD CONSTRAINT DIM_CUSTOMERS_PK PRIMARY KEY ( CUSTOMER_SURR_ID );