CREATE TABLE BL_3NF.CE_CHANNEL_CLASSES (
    CHANNEL_CLASS_ID            NUMBER(38) NOT NULL,
    CHANNEL_CLASS_SRCID         VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_CLASS_SOURCE_SYSTEM VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_CLASS_SOURCE_ENTITY VARCHAR2(50 CHAR) NOT NULL,
    CHANNEL_CLASS               VARCHAR2(50 CHAR) NOT NULL,
    TA_UPDATE_DT                DATE NOT NULL,
    TA_INSERT_DT                DATE NOT NULL
);

ALTER TABLE BL_3NF.CE_CHANNEL_CLASSES ADD CONSTRAINT CE_CHANNEL_CLASS_PK PRIMARY KEY ( CHANNEL_CLASS_ID );
