CREATE TABLE BL_DM.DIM_EMPLOYEES (
    EMPLOYEE_SURR_ID   NUMBER(38)   NOT NULL,
    EMPLOYEE_SRCID     VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM      VARCHAR2(50) NOT NULL,
    SOURCE_ENTITY      VARCHAR2(50) NOT NULL,
    FIRST_NAME         VARCHAR2(50) NOT NULL,
    LAST_NAME          VARCHAR2(50) NOT NULL,
    DAY_OF_BIRTHDAY_DT DATE         NOT NULL,
    POSITION_ID        NUMBER(38)   NOT NULL,
    POSITION           VARCHAR2(50) NOT NULL,
    PHONE              VARCHAR2(50) NOT NULL,
    EMAIL              VARCHAR2(50) NOT NULL,
    ADDRESS            VARCHAR2(50) NOT NULL,
    COUNTRY_ID         NUMBER(38)   NOT NULL,
    COUNTRY            VARCHAR2(50) NOT NULL,
    TA_UPDATE_DT       DATE         NOT NULL,
    TA_INSERT_DT       DATE         NOT NULL
);

ALTER TABLE BL_DM.DIM_EMPLOYEES ADD CONSTRAINT DIM_EMPLOYEES_SCD_PK PRIMARY KEY ( EMPLOYEE_SURR_ID );
